name: CI Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: CI Workflow
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Set BASE_URL environment variable
        run: echo "BASE_URL=${{ secrets.BASE_URL }}" >> .env

      - name: Display .env file
        env:
            DB_USER: ${{ secrets.DB_USER }}
            DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
            DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          echo "DB_USER=root" >> .env
          echo "DB_PASSWORD=root" >> .env
          echo "DB_NAME=webapp" >> .env
          echo "PORT=3306" >> .env
          echo "DB_HOST=localhost" >> .env
          echo "BASE_URL=http://localhost:3000" >> .env
          cat .env
      
      # - name: Save .env in the repository
      #   run: mv .env $GITHUB_WORKSPACE/.env
        

      - name: Configure MySQL
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          sudo systemctl start mysql
          sudo systemctl status mysql
          mysql -u root -p"root" -e "CREATE DATABASE webapp;"

      - name: Run Unit Tests
        run: npm run test:unit
        env:
          BASE_URL: http://localhost:3000