name: Packer Status Check

on:
  pull_request:
    branches:
      - main

jobs:
  packer-status-check:
    name: Packer Status Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Print Current Directory
        run: |
          pwd
          ls -l
        shell: bash

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: '1.8.6'

      - name: Initialize Packer
        run: packer init -upgrade packer/aws-debian.pkr.hcl

      - name: Run 'packer fmt'
        run: |
          if packer fmt -check packer/aws-debian.pkr.hcl; then
            echo "Packer template is formatted correctly."
          else
            echo "Packer template is not formatted correctly. Please format the template and try again."
            exit 1
          fi
       
      - name: Create ZIP Archive
        run: zip -r webapp.zip .

      - name: Print Contents of Directory
        run: ls -l

      - name: Run 'packer validate'
        run: |
          if packer validate packer/aws-debian.pkr.hcl; then
            echo "Packer template is valid."
          else
            echo "Packer template is not valid. Please fix the issues in the template and try again."
            exit 1
          fi
      
      - name: Build AMI with Packer
        run: packer build packer/aws-debian.pkr.hcl
        continue-on-error: false # Fail the workflow if Packer build fails
        id: packer-build