name: Packer Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  packer:
    name: Packer Workflow
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Print Current Directory
        run: |
          pwd
          ls -l
        shell: bash

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: '1.8.6'

      - name: Create ZIP Archive
        run: zip -r webapp.zip .

      - name: Initialize Packer
        run: packer init .

      - name: Run 'packer fmt'
        run: |
          packer fmt -check aws-debian.pkr.hcl

      - name: Print Contents of Directory
        run: ls -l ${{ github.workspace }}

      - name: Check file existence and permissions
        run: |
          ls -l /home/admin/webapp/
        shell: bash

      - name: Print the content of the zip file
        run: |
          unzip -l /home/admin/webapp/webapp.zip
        shell: bash

      - name: Run 'packer validate'
        run: |
          packer validate aws-debian.pkr.hcl
